### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by Stepkaa** [devajyotibarman/Whatzap#1]
/home/User/Desktop/whatsappz/Whatzap-master/whatzapwindow.h:8: error: QWebEngineProfile: No such file or directory
 #include <QWebEngineProfile>
                             ^

**Comment by devajyotibarman** [comment]
Hi Mark

Which version of Qt are you using?
QWebengine was intruduced in Qt5 (I think)

If you are using 5.1 or higher, try adding the qwebengine in the .pro file.
