### ISSUE TITLE
no type error with QWebEnginePage object

### ISSUE THREAD

**Issue by NilanjPatel** [devajyotibarman/Whatzap#2]
../Whatzap/whatzapwindow.h:64:58: error: no type named 'RenderProcessTerminationStatus' in 'QWebEnginePage'
    void renderProcessTerminationHandler(QWebEnginePage::RenderProcessTerminationStatus termStatus,
                                         ~~~~~~~~~~~~~~~~^

**Comment by devajyotibarman** [comment]
Hi,

Could you please tell me which Qt Version you are using?

**Comment by NilanjPatel** [comment]
i am using qt 5.5.1
![Uploading Screen Shot 2016-11-25 at 1.05.29 PM.png…]()

**Comment by devajyotibarman** [comment]
I think that was add in 5.6 and later. The app can run without that handler so you can remove the code itself from the header and source file. 

If you look at the diff I added it much later.
